#!/bin/sh
# File: headmail
# Description: This adds a mail header to input.
# Author: Ben O'Neill <ben@benoneill.xyz>
# Copyright: Copyright (C) 2019-2020 Ben O'Neill <benoneill.xyz>. Licensed under
# GNU GPL v3.

from="$1"
to="$2"

[ -z "$from" ] && echo "A sender must be provided" 1>&2 && exit 1
[ -z "$to" ] && echo "A recipient must be provided" 1>&2 && exit 1

[ -z "$3" ] && subject="Unofficial MBTA Alert Digest" || subject="$3"

printf "From: $from\nTo: $to\nSubject: $subject\n\n\n"
cat
