#!/bin/sh
# File: md2mail
# Description: This converts Markdown input into a plain Markdown digest to be sent by email.
# Author: Ben O'Neill <ben@benoneill.xyz>
# Copyright: Copyright (C) 2019-2020 Ben O'Neill <benoneill.xyz>. Licensed under
# GNU GPL v3.

from="$1"
to="$2"
[ -z "$3" ] && subject="Unofficial MBTA Alert Digest" || subject="$3"

printf "From: $from\nTo: $to\nSubject: $subject\n\n\n"
cat
